package db.migration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.myagent.modelcatalog.application.ModelCatalogBootstrapDefaults;
import com.myagent.modelcatalog.application.ModelCatalogKeyNormalizer;
import com.myagent.modelcatalog.secret.ModelProviderSecretCodec;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

/**
 * 模型供应商目录与运行路由 V1 迁移。
 */
public class V4__model_provider_catalog_routing_v1 extends BaseJavaMigration {

    /**
     * JSON 对象映射器。
     */
    private final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * 执行迁移。
     *
     * @param context Flyway 上下文
     * @throws Exception 迁移失败时抛出
     */
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        createModelCatalogTables(connection);
        String legacyModel = readLegacyDefaultModel(connection);
        LegacyOfferingMappings offeringMappings = bootstrapDefaultCatalog(connection, legacyModel);
        migrateAgentDefaultModel(connection, offeringMappings);
        migrateWorkflowNodeModels(connection, offeringMappings);
        migrateEvalScoreRuleModels(connection, offeringMappings);
        cleanupLegacySettings(connection);
        addForeignKeys(connection);
        dropLegacyAgentDefaultModelColumn(connection);
    }

    /**
     * 创建模型目录表。
     *
     * @param connection 数据库连接
     * @throws SQLException 执行失败时抛出
     */
    private void createModelCatalogTables(Connection connection) throws SQLException {
        execute(connection, """
                create table if not exists model_provider (
                  id bigint generated by default as identity primary key,
                  provider_key varchar(128) not null,
                  name varchar(200) not null,
                  provider_type varchar(40) not null,
                  base_url varchar(500) not null,
                  api_key_ciphertext text not null default '',
                  api_key_mask varchar(80) not null default '',
                  status varchar(20) not null,
                  description text not null default '',
                  created_at timestamptz not null default now(),
                  updated_at timestamptz not null default now(),
                  constraint uq_model_provider_provider_key unique (provider_key),
                  constraint ck_model_provider_type check (provider_type in ('OPENAI_COMPATIBLE')),
                  constraint ck_model_provider_status check (status in ('ENABLED', 'DISABLED'))
                )
                """);
        execute(connection, """
                create index if not exists idx_model_provider_status on model_provider(status)
                """);
        execute(connection, """
                create index if not exists idx_model_provider_type_status on model_provider(provider_type, status)
                """);
        execute(connection, """
                create table if not exists model_offering (
                  id bigint generated by default as identity primary key,
                  offering_key varchar(128) not null,
                  provider_key varchar(128) not null,
                  model_key varchar(128) not null,
                  display_name varchar(200) not null,
                  upstream_model_name varchar(200) not null,
                  default_temperature numeric(4,2),
                  status varchar(20) not null,
                  description text not null default '',
                  created_at timestamptz not null default now(),
                  updated_at timestamptz not null default now(),
                  constraint uq_model_offering_key unique (offering_key),
                  constraint uq_model_offering_provider_upstream unique (provider_key, upstream_model_name),
                  constraint ck_model_offering_status check (status in ('ENABLED', 'DISABLED')),
                  constraint ck_model_offering_temperature check (
                    default_temperature is null or (default_temperature >= 0 and default_temperature <= 2)
                  )
                )
                """);
        execute(connection, """
                create index if not exists idx_model_offering_provider_status on model_offering(provider_key, status)
                """);
        execute(connection, """
                create index if not exists idx_model_offering_model_status on model_offering(model_key, status)
                """);
        execute(connection, """
                alter table agent_definition
                add column if not exists default_model_offering_key varchar(128)
                """);
    }

    /**
     * 创建默认目录记录。
     *
     * @param connection 数据库连接
     * @param legacyDefaultModel 旧默认模型
     * @return 默认目录状态
     * @throws SQLException 执行失败时抛出
     */
    private LegacyOfferingMappings bootstrapDefaultCatalog(Connection connection, String legacyDefaultModel) throws Exception {
        String defaultModelName = ModelCatalogBootstrapDefaults.normalizeModel(firstNonBlank(
                System.getenv("AGENT_STUDIO_OPENAI_DEFAULT_MODEL"),
                legacyDefaultModel
        ));
        String baseUrl = ModelCatalogBootstrapDefaults.normalizeBaseUrl(System.getenv("AGENT_STUDIO_OPENAI_BASE_URL"));
        String apiKey = trimToEmpty(System.getenv("AGENT_STUDIO_OPENAI_API_KEY"));
        String ciphertext = "";
        String apiKeyMask = "";
        if (!apiKey.isBlank()) {
            byte[] masterKey = ModelProviderSecretCodec.decodeMasterKey(System.getenv("AGENT_STUDIO_SECRET_KEY"));
            ciphertext = ModelProviderSecretCodec.encrypt(apiKey, masterKey);
            apiKeyMask = ModelProviderSecretCodec.mask(apiKey);
        }

        Set<String> legacyModels = collectLegacyModels(connection);
        legacyModels.add(defaultModelName);
        upsertDefaultProvider(connection, baseUrl, ciphertext, apiKeyMask);
        LegacyOfferingMappings mappings = buildLegacyOfferingMappings(legacyModels, defaultModelName);
        for (Map.Entry<String, String> entry : mappings.byModelName().entrySet()) {
            upsertDefaultOffering(connection, entry.getValue(), entry.getKey());
        }
        return mappings;
    }

    /**
     * 迁移 Agent 默认模型。
     *
     * @param connection 数据库连接
     * @param defaultOfferingKey 默认供应项键
     * @throws SQLException 执行失败时抛出
     */
    private void migrateAgentDefaultModel(Connection connection, LegacyOfferingMappings mappings) throws SQLException {
        try (PreparedStatement query = connection.prepareStatement("""
                select id, default_model
                from agent_definition
                order by id
                """);
             ResultSet resultSet = query.executeQuery()) {
            while (resultSet.next()) {
                long agentId = resultSet.getLong("id");
                String offeringKey = mappings.resolve(trimToEmpty(resultSet.getString("default_model")));
                try (PreparedStatement update = connection.prepareStatement("""
                        update agent_definition
                        set default_model_offering_key = ?
                        where id = ?
                        """)) {
                    if (offeringKey.isBlank()) {
                        update.setNull(1, java.sql.Types.VARCHAR);
                    } else {
                        update.setString(1, offeringKey);
                    }
                    update.setLong(2, agentId);
                    update.executeUpdate();
                }
            }
        }
    }

    /**
     * 迁移工作流节点模型字段。
     *
     * @param connection 数据库连接
     * @param defaultOfferingKey 默认供应项键
     * @throws Exception 执行失败时抛出
     */
    private void migrateWorkflowNodeModels(Connection connection, LegacyOfferingMappings mappings) throws Exception {
        try (PreparedStatement query = connection.prepareStatement("""
                select id, nodes_json
                from workflow_version
                order by id
                """);
             ResultSet resultSet = query.executeQuery()) {
            while (resultSet.next()) {
                long workflowVersionId = resultSet.getLong("id");
                JsonNode nodesJson = objectMapper.readTree(resultSet.getString("nodes_json"));
                JsonNode migrated = migrateWorkflowNodesJson(nodesJson, mappings);
                try (PreparedStatement update = connection.prepareStatement("""
                        update workflow_version
                        set nodes_json = cast(? as jsonb),
                            updated_at = now()
                        where id = ?
                        """)) {
                    update.setString(1, objectMapper.writeValueAsString(migrated));
                    update.setLong(2, workflowVersionId);
                    update.executeUpdate();
                }
            }
        }
    }

    /**
     * 迁移 Eval 评分规则模型字段。
     *
     * @param connection 数据库连接
     * @param defaultOfferingKey 默认供应项键
     * @throws Exception 执行失败时抛出
     */
    private void migrateEvalScoreRuleModels(Connection connection, LegacyOfferingMappings mappings) throws Exception {
        try (PreparedStatement query = connection.prepareStatement("""
                select id, score_rule_json
                from eval_case
                order by id
                """);
             ResultSet resultSet = query.executeQuery()) {
            while (resultSet.next()) {
                long evalCaseId = resultSet.getLong("id");
                JsonNode scoreRuleJson = objectMapper.readTree(resultSet.getString("score_rule_json"));
                JsonNode migrated = migrateScoreRuleJson(scoreRuleJson, mappings);
                try (PreparedStatement update = connection.prepareStatement("""
                        update eval_case
                        set score_rule_json = cast(? as jsonb),
                            updated_at = now()
                        where id = ?
                        """)) {
                    update.setString(1, objectMapper.writeValueAsString(migrated));
                    update.setLong(2, evalCaseId);
                    update.executeUpdate();
                }
            }
        }
    }

    /**
     * 清理旧设置键。
     *
     * @param connection 数据库连接
     * @throws SQLException 执行失败时抛出
     */
    private void cleanupLegacySettings(Connection connection) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                delete from system_setting
                where setting_key = 'agent.studio.openai.default-model'
                """)) {
            statement.executeUpdate();
        }
    }

    /**
     * 增加外键。
     *
     * @param connection 数据库连接
     * @throws SQLException 执行失败时抛出
     */
    private void addForeignKeys(Connection connection) throws SQLException {
        if (!constraintExists(connection, "fk_model_offering_provider")) {
            execute(connection, """
                    alter table model_offering
                    add constraint fk_model_offering_provider
                    foreign key (provider_key) references model_provider(provider_key)
                    """);
        }
        if (!constraintExists(connection, "fk_agent_definition_default_model_offering")) {
            execute(connection, """
                    alter table agent_definition
                    add constraint fk_agent_definition_default_model_offering
                    foreign key (default_model_offering_key) references model_offering(offering_key)
                    """);
        }
    }

    /**
     * 删除旧 Agent 默认模型列。
     *
     * @param connection 数据库连接
     * @throws SQLException 执行失败时抛出
     */
    private void dropLegacyAgentDefaultModelColumn(Connection connection) throws SQLException {
        execute(connection, """
                alter table agent_definition
                drop column if exists default_model
                """);
    }

    /**
     * 查询旧默认模型。
     *
     * @param connection 数据库连接
     * @return 默认模型
     * @throws SQLException 执行失败时抛出
     */
    private String readLegacyDefaultModel(Connection connection) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select setting_value
                from system_setting
                where setting_key = 'agent.studio.openai.default-model'
                """);
             ResultSet resultSet = statement.executeQuery()) {
            if (resultSet.next()) {
                return trimToEmpty(resultSet.getString(1));
            }
            return "";
        }
    }

    /**
     * 插入或更新默认供应商。
     *
     * @param connection 数据库连接
     * @param baseUrl Base URL
     * @param ciphertext 密文
     * @param apiKeyMask 掩码
     * @throws SQLException 执行失败时抛出
     */
    private void upsertDefaultProvider(Connection connection, String baseUrl, String ciphertext, String apiKeyMask) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into model_provider(
                  provider_key, name, provider_type, base_url, api_key_ciphertext, api_key_mask, status, description
                )
                values (?, ?, 'OPENAI_COMPATIBLE', ?, ?, ?, 'ENABLED', '')
                on conflict (provider_key) do update
                set name = excluded.name,
                    provider_type = excluded.provider_type,
                    base_url = excluded.base_url,
                    api_key_ciphertext = case
                        when excluded.api_key_ciphertext <> '' then excluded.api_key_ciphertext
                        else model_provider.api_key_ciphertext
                    end,
                    api_key_mask = case
                        when excluded.api_key_mask <> '' then excluded.api_key_mask
                        else model_provider.api_key_mask
                    end,
                    updated_at = now()
                """)) {
            statement.setString(1, ModelCatalogBootstrapDefaults.DEFAULT_PROVIDER_KEY);
            statement.setString(2, ModelCatalogBootstrapDefaults.DEFAULT_PROVIDER_NAME);
            statement.setString(3, baseUrl);
            statement.setString(4, ciphertext);
            statement.setString(5, apiKeyMask);
            statement.executeUpdate();
        }
    }

    /**
     * 插入或更新默认供应项。
     *
     * @param connection 数据库连接
     * @param offeringKey 供应项键
     * @param modelName 模型名
     * @throws SQLException 执行失败时抛出
     */
    private void upsertDefaultOffering(Connection connection, String offeringKey, String modelName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into model_offering(
                  offering_key, provider_key, model_key, display_name, upstream_model_name, default_temperature, status, description
                )
                values (?, ?, ?, ?, ?, null, 'ENABLED', '')
                on conflict (offering_key) do update
                set provider_key = excluded.provider_key,
                    model_key = excluded.model_key,
                    display_name = excluded.display_name,
                    upstream_model_name = excluded.upstream_model_name,
                    updated_at = now()
                """)) {
            statement.setString(1, offeringKey);
            statement.setString(2, ModelCatalogBootstrapDefaults.DEFAULT_PROVIDER_KEY);
            statement.setString(3, ModelCatalogKeyNormalizer.toModelKey(modelName));
            statement.setString(4, modelName);
            statement.setString(5, modelName);
            statement.executeUpdate();
        }
    }

    /**
     * 收集全部旧模型名。
     *
     * @param connection 数据库连接
     * @return 模型名集合
     * @throws Exception 执行失败时抛出
     */
    private Set<String> collectLegacyModels(Connection connection) throws Exception {
        LinkedHashSet<String> legacyModels = new LinkedHashSet<>();
        addIfNotBlank(legacyModels, readLegacyDefaultModel(connection));
        try (PreparedStatement query = connection.prepareStatement("""
                select default_model
                from agent_definition
                """);
             ResultSet resultSet = query.executeQuery()) {
            while (resultSet.next()) {
                addIfNotBlank(legacyModels, resultSet.getString(1));
            }
        }
        try (PreparedStatement query = connection.prepareStatement("""
                select nodes_json
                from workflow_version
                """);
             ResultSet resultSet = query.executeQuery()) {
            while (resultSet.next()) {
                JsonNode nodesJson = objectMapper.readTree(resultSet.getString(1));
                if (nodesJson == null || !nodesJson.isArray()) {
                    continue;
                }
                for (JsonNode node : nodesJson) {
                    addIfNotBlank(legacyModels, textValue(node.path("config").path("model")));
                }
            }
        }
        try (PreparedStatement query = connection.prepareStatement("""
                select score_rule_json
                from eval_case
                """);
             ResultSet resultSet = query.executeQuery()) {
            while (resultSet.next()) {
                JsonNode scoreRuleJson = objectMapper.readTree(resultSet.getString(1));
                addIfNotBlank(legacyModels, textValue(scoreRuleJson.path("model")));
            }
        }
        return legacyModels;
    }

    /**
     * 构造历史模型到供应项键的映射。
     *
     * @param modelNames 模型名集合
     * @param defaultModelName 默认模型名
     * @return 映射结果
     */
    private LegacyOfferingMappings buildLegacyOfferingMappings(Set<String> modelNames, String defaultModelName) {
        LinkedHashMap<String, String> byModelName = new LinkedHashMap<>();
        LinkedHashSet<String> usedOfferingKeys = new LinkedHashSet<>();
        for (String rawModelName : modelNames) {
            String normalizedModelName = ModelCatalogBootstrapDefaults.normalizeModel(rawModelName);
            String baseOfferingKey = ModelCatalogKeyNormalizer.toOfferingKey(
                    ModelCatalogBootstrapDefaults.DEFAULT_PROVIDER_NAMESPACE,
                    normalizedModelName
            );
            String offeringKey = baseOfferingKey;
            int suffix = 2;
            while (usedOfferingKeys.contains(offeringKey)) {
                String existingModelName = findModelNameByOfferingKey(byModelName, offeringKey);
                if (normalizedModelName.equals(existingModelName)) {
                    break;
                }
                offeringKey = baseOfferingKey + "_" + suffix;
                suffix++;
            }
            usedOfferingKeys.add(offeringKey);
            byModelName.put(normalizedModelName, offeringKey);
        }
        String normalizedDefaultModelName = ModelCatalogBootstrapDefaults.normalizeModel(defaultModelName);
        return new LegacyOfferingMappings(byModelName, byModelName.get(normalizedDefaultModelName));
    }

    /**
     * 通过供应项键反查模型名。
     *
     * @param byModelName 模型映射
     * @param offeringKey 供应项键
     * @return 模型名
     */
    private String findModelNameByOfferingKey(Map<String, String> byModelName, String offeringKey) {
        for (Map.Entry<String, String> entry : byModelName.entrySet()) {
            if (offeringKey.equals(entry.getValue())) {
                return entry.getKey();
            }
        }
        return "";
    }

    /**
     * 迁移工作流节点数组 JSON。
     *
     * @param nodesJson 节点数组
     * @param mappings 历史映射
     * @return 迁移后的数组
     */
    private JsonNode migrateWorkflowNodesJson(JsonNode nodesJson, LegacyOfferingMappings mappings) {
        if (nodesJson == null || !nodesJson.isArray()) {
            return objectMapper.createArrayNode();
        }
        ArrayNode migrated = objectMapper.createArrayNode();
        for (JsonNode node : nodesJson) {
            if (!(node instanceof ObjectNode objectNode)) {
                migrated.add(node);
                continue;
            }
            JsonNode configNode = objectNode.get("config");
            if (configNode instanceof ObjectNode configObjectNode) {
                String legacyModel = trimToEmpty(textValue(configObjectNode.get("model")));
                if (!legacyModel.isBlank()) {
                    configObjectNode.put("modelOfferingKey", mappings.resolve(legacyModel));
                }
                configObjectNode.remove("model");
            }
            migrated.add(objectNode);
        }
        return migrated;
    }

    /**
     * 迁移评分规则 JSON。
     *
     * @param scoreRuleJson 评分规则
     * @param mappings 历史映射
     * @return 迁移后的评分规则
     */
    private JsonNode migrateScoreRuleJson(JsonNode scoreRuleJson, LegacyOfferingMappings mappings) {
        if (!(scoreRuleJson instanceof ObjectNode objectNode)) {
            return objectMapper.createObjectNode();
        }
        String legacyModel = trimToEmpty(textValue(objectNode.get("model")));
        if (!legacyModel.isBlank()) {
            objectNode.put("modelOfferingKey", mappings.resolve(legacyModel));
        }
        objectNode.remove("model");
        return objectNode;
    }

    /**
     * 判断约束是否存在。
     *
     * @param connection 数据库连接
     * @param constraintName 约束名
     * @return 存在时返回 true
     * @throws SQLException 执行失败时抛出
     */
    private boolean constraintExists(Connection connection, String constraintName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select count(*)
                from information_schema.table_constraints
                where constraint_schema = 'public'
                  and constraint_name = ?
                """)) {
            statement.setString(1, constraintName);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getInt(1) > 0;
            }
        }
    }

    /**
     * 执行无参 SQL。
     *
     * @param connection 数据库连接
     * @param sql SQL 语句
     * @throws SQLException 执行失败时抛出
     */
    private void execute(Connection connection, String sql) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.executeUpdate();
        }
    }

    /**
     * 返回首个非空白字符串。
     *
     * @param values 候选值
     * @return 首个非空白字符串
     */
    private String firstNonBlank(String... values) {
        for (String value : values) {
            if (value != null && !value.isBlank()) {
                return value.trim();
            }
        }
        return "";
    }

    /**
     * 读取 JSON 文本值。
     *
     * @param jsonNode JSON 节点
     * @return 文本值
     */
    private String textValue(JsonNode jsonNode) {
        if (jsonNode != null && jsonNode.isTextual()) {
            return jsonNode.asText();
        }
        return "";
    }

    /**
     * 去除首尾空白。
     *
     * @param value 原始值
     * @return 处理结果
     */
    private String trimToEmpty(String value) {
        return value == null ? "" : value.trim();
    }

    /**
     * 非空模型名才加入集合。
     *
     * @param models 模型集合
     * @param modelName 模型名
     */
    private void addIfNotBlank(Set<String> models, String modelName) {
        if (modelName != null && !modelName.isBlank()) {
            models.add(ModelCatalogBootstrapDefaults.normalizeModel(modelName));
        }
    }

    /**
     * 历史模型映射。
     *
     * @param byModelName 模型名到供应项键的映射
     * @param defaultOfferingKey 默认供应项键
     */
    private record LegacyOfferingMappings(Map<String, String> byModelName, String defaultOfferingKey) {

        /**
         * 解析模型名对应的供应项键。
         *
         * @param modelName 模型名
         * @return 供应项键
         */
        private String resolve(String modelName) {
            if (modelName == null || modelName.isBlank()) {
                return "";
            }
            return byModelName.getOrDefault(
                    ModelCatalogBootstrapDefaults.normalizeModel(modelName),
                    defaultOfferingKey == null ? "" : defaultOfferingKey
            );
        }
    }
}
