create table schema_definition (
  id bigint generated by default as identity primary key,
  schema_key varchar(128) not null,
  version integer not null,
  name varchar(200) not null,
  description text not null default '',
  json_schema jsonb not null,
  java_type varchar(255) not null default '',
  created_from varchar(40) not null,
  status varchar(20) not null,
  locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_schema_definition_key_version unique (schema_key, version),
  constraint ck_schema_definition_created_from check (
    created_from in (
      'USER_CREATED',
      'JAVA_METHOD_SCAN',
      'TOOL_DEFINITION',
      'SYSTEM_BUILTIN',
      'AGENT_INPUT',
      'AGENT_OUTPUT'
    )
  ),
  constraint ck_schema_definition_status check (status in ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

create index idx_schema_definition_key_version_desc on schema_definition(schema_key, version desc);
create index idx_schema_definition_created_from_status on schema_definition(created_from, status);
create index idx_schema_definition_status_locked on schema_definition(status, locked);

create table java_method_definition (
  id bigint generated by default as identity primary key,
  method_key varchar(128) not null,
  name varchar(200) not null,
  description text not null default '',
  bean_name varchar(200) not null,
  method_name varchar(200) not null,
  input_schema_id bigint not null,
  output_schema_id bigint not null,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_java_method_definition_method_key unique (method_key),
  constraint ck_java_method_definition_status check (status in ('ENABLED', 'DISABLED')),
  constraint fk_java_method_definition_input_schema foreign key (input_schema_id) references schema_definition(id),
  constraint fk_java_method_definition_output_schema foreign key (output_schema_id) references schema_definition(id)
);

create index idx_java_method_definition_status on java_method_definition(status);
create index idx_java_method_definition_bean_method on java_method_definition(bean_name, method_name);
create index idx_java_method_definition_input_schema on java_method_definition(input_schema_id);
create index idx_java_method_definition_output_schema on java_method_definition(output_schema_id);

create table tool_definition (
  id bigint generated by default as identity primary key,
  tool_key varchar(128) not null,
  name varchar(200) not null,
  description text not null default '',
  input_schema_id bigint not null,
  output_schema_id bigint not null,
  executor_type varchar(40) not null,
  executor_config_json jsonb not null default '{}'::jsonb,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_tool_definition_tool_key unique (tool_key),
  constraint ck_tool_definition_status check (status in ('ENABLED', 'DISABLED')),
  constraint fk_tool_definition_input_schema foreign key (input_schema_id) references schema_definition(id),
  constraint fk_tool_definition_output_schema foreign key (output_schema_id) references schema_definition(id)
);

create index idx_tool_definition_status on tool_definition(status);
create index idx_tool_definition_executor_type on tool_definition(executor_type);
create index idx_tool_definition_input_schema on tool_definition(input_schema_id);
create index idx_tool_definition_output_schema on tool_definition(output_schema_id);

create table external_agent_definition (
  id bigint generated by default as identity primary key,
  adapter_key varchar(128) not null,
  adapter_type varchar(40) not null,
  name varchar(200) not null,
  description text not null default '',
  command_json jsonb not null default '{}'::jsonb,
  working_directory varchar(500) not null default '',
  timeout_seconds integer not null default 600,
  capture_stdout boolean not null default false,
  capture_stderr boolean not null default false,
  capture_git_diff boolean not null default false,
  output_schema_id bigint,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_external_agent_definition_adapter_key unique (adapter_key),
  constraint ck_external_agent_definition_adapter_type check (
    adapter_type in ('CODEX_CLI', 'OPENCODE_CLI', 'CUSTOM_CLI', 'CUSTOM_HTTP')
  ),
  constraint ck_external_agent_definition_status check (status in ('ENABLED', 'DISABLED')),
  constraint ck_external_agent_definition_timeout_seconds check (timeout_seconds > 0),
  constraint fk_external_agent_definition_output_schema foreign key (output_schema_id) references schema_definition(id)
);

create index idx_external_agent_definition_adapter_type_status
  on external_agent_definition(adapter_type, status);
create index idx_external_agent_definition_status on external_agent_definition(status);
create index idx_external_agent_definition_output_schema on external_agent_definition(output_schema_id);

create table agent_definition (
  id bigint generated by default as identity primary key,
  agent_key varchar(128) not null,
  name varchar(200) not null,
  description text not null default '',
  status varchar(20) not null,
  system_prompt text not null default '',
  default_model varchar(128) not null default '',
  temperature numeric(4,2),
  timeout_seconds integer not null default 600,
  max_steps integer not null default 30,
  current_draft_workflow_version_id bigint,
  current_published_workflow_version_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_agent_definition_agent_key unique (agent_key),
  constraint ck_agent_definition_status check (status in ('ENABLED', 'DISABLED')),
  constraint ck_agent_definition_timeout_seconds check (timeout_seconds > 0),
  constraint ck_agent_definition_max_steps check (max_steps > 0),
  constraint ck_agent_definition_temperature check (
    temperature is null or (temperature >= 0 and temperature <= 2)
  )
);

create index idx_agent_definition_status on agent_definition(status);
create index idx_agent_definition_updated_at_desc on agent_definition(updated_at desc);

create table workflow_version (
  id bigint generated by default as identity primary key,
  agent_id bigint not null,
  version_no integer not null,
  status varchar(20) not null,
  nodes_json jsonb not null default '[]'::jsonb,
  edges_json jsonb not null default '[]'::jsonb,
  runtime_options_json jsonb not null default '{}'::jsonb,
  referenced_schema_versions_json jsonb not null default '[]'::jsonb,
  source_workflow_version_id bigint,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_workflow_version_agent_version unique (agent_id, version_no),
  constraint ck_workflow_version_status check (status in ('DRAFT', 'PUBLISHED', 'HISTORY')),
  constraint fk_workflow_version_agent foreign key (agent_id) references agent_definition(id),
  constraint fk_workflow_version_source foreign key (source_workflow_version_id) references workflow_version(id)
);

create index idx_workflow_version_agent_status_version on workflow_version(agent_id, status, version_no);
create index idx_workflow_version_agent_created_at_desc on workflow_version(agent_id, created_at desc);
create index idx_workflow_version_source on workflow_version(source_workflow_version_id);

create unique index uq_workflow_version_one_draft
  on workflow_version(agent_id)
  where status = 'DRAFT';

create unique index uq_workflow_version_one_published
  on workflow_version(agent_id)
  where status = 'PUBLISHED';

alter table agent_definition
  add constraint fk_agent_definition_current_draft_workflow
  foreign key (current_draft_workflow_version_id) references workflow_version(id)
  deferrable initially deferred;

alter table agent_definition
  add constraint fk_agent_definition_current_published_workflow
  foreign key (current_published_workflow_version_id) references workflow_version(id)
  deferrable initially deferred;

create index idx_agent_definition_current_draft_workflow
  on agent_definition(current_draft_workflow_version_id);
create index idx_agent_definition_current_published_workflow
  on agent_definition(current_published_workflow_version_id);

create table system_setting (
  setting_key varchar(128) primary key,
  setting_value text not null,
  value_type varchar(20) not null,
  description text not null default '',
  editable boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint ck_system_setting_value_type check (value_type in ('STRING', 'NUMBER', 'BOOLEAN', 'JSON'))
);

create index idx_system_setting_editable on system_setting(editable);

create table agent_run (
  id bigint generated by default as identity primary key,
  run_no varchar(64) not null,
  agent_id bigint not null,
  agent_key varchar(128) not null,
  workflow_version_id bigint not null,
  parent_run_id bigint,
  run_type varchar(20) not null,
  input_json jsonb not null default '{}'::jsonb,
  output_json jsonb,
  status varchar(20) not null,
  error_message text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint,
  constraint uq_agent_run_run_no unique (run_no),
  constraint ck_agent_run_run_type check (run_type in ('DEBUG', 'API', 'AGENT_CALL', 'EVAL')),
  constraint ck_agent_run_status check (
    status in ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELED')
  ),
  constraint fk_agent_run_agent foreign key (agent_id) references agent_definition(id),
  constraint fk_agent_run_workflow_version foreign key (workflow_version_id) references workflow_version(id),
  constraint fk_agent_run_parent foreign key (parent_run_id) references agent_run(id)
);

create index idx_agent_run_agent_status_started_at_desc on agent_run(agent_id, status, started_at desc);
create index idx_agent_run_agent_key_run_type_started_at_desc on agent_run(agent_key, run_type, started_at desc);
create index idx_agent_run_workflow_version_started_at_desc on agent_run(workflow_version_id, started_at desc);
create index idx_agent_run_parent on agent_run(parent_run_id);

create table node_run (
  id bigint generated by default as identity primary key,
  run_id bigint not null,
  node_id varchar(128) not null,
  node_name varchar(200) not null,
  node_type varchar(40) not null,
  input_json jsonb not null default '{}'::jsonb,
  output_json jsonb,
  schema_validation_result_json jsonb,
  status varchar(20) not null,
  error_message text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint,
  constraint ck_node_run_status check (
    status in ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELED')
  ),
  constraint fk_node_run_agent_run foreign key (run_id) references agent_run(id)
);

create index idx_node_run_run_started_at_asc on node_run(run_id, started_at asc);
create index idx_node_run_run_node on node_run(run_id, node_id);
create index idx_node_run_node_type_status on node_run(node_type, status);

create table trace_event (
  id bigint generated by default as identity primary key,
  run_id bigint,
  node_run_id bigint,
  eval_run_id bigint,
  event_type varchar(40) not null,
  summary varchar(500) not null,
  detail_json jsonb not null default '{}'::jsonb,
  event_time timestamptz not null default now(),
  constraint ck_trace_event_type check (
    event_type in (
      'MODEL_REQUEST',
      'MODEL_RESPONSE',
      'SCHEMA_VALIDATION',
      'CONDITION_DECISION',
      'JAVA_METHOD_CALL',
      'TOOL_CALL',
      'EXTERNAL_AGENT_CALL',
      'AGENT_CALL',
      'EVAL_CASE_RESULT',
      'NODE_ERROR',
      'RUN_FINISHED'
    )
  ),
  constraint fk_trace_event_agent_run foreign key (run_id) references agent_run(id),
  constraint fk_trace_event_node_run foreign key (node_run_id) references node_run(id)
);

create index idx_trace_event_run_event_time_asc on trace_event(run_id, event_time asc);
create index idx_trace_event_node_run_event_time_asc on trace_event(node_run_id, event_time asc);
create index idx_trace_event_eval_run_event_time_asc on trace_event(eval_run_id, event_time asc);
create index idx_trace_event_type_event_time_desc on trace_event(event_type, event_time desc);

create table agent_message (
  id bigint generated by default as identity primary key,
  parent_run_id bigint not null,
  child_run_id bigint not null,
  source_agent_id bigint not null,
  target_agent_id bigint not null,
  input_json jsonb not null default '{}'::jsonb,
  output_json jsonb,
  summary text not null default '',
  created_at timestamptz not null default now(),
  constraint uq_agent_message_child_run unique (child_run_id),
  constraint fk_agent_message_parent_run foreign key (parent_run_id) references agent_run(id),
  constraint fk_agent_message_child_run foreign key (child_run_id) references agent_run(id),
  constraint fk_agent_message_source_agent foreign key (source_agent_id) references agent_definition(id),
  constraint fk_agent_message_target_agent foreign key (target_agent_id) references agent_definition(id)
);

create index idx_agent_message_parent_run_created_at_asc on agent_message(parent_run_id, created_at asc);
create index idx_agent_message_child_run on agent_message(child_run_id);
create index idx_agent_message_source_target_agent on agent_message(source_agent_id, target_agent_id);

create table eval_suite (
  id bigint generated by default as identity primary key,
  agent_id bigint not null,
  workflow_version_id bigint not null,
  node_id varchar(128) not null,
  name varchar(200) not null,
  goal text not null default '',
  pass_threshold numeric(5,2) not null default 0,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_eval_suite_status check (status in ('DRAFT', 'CONFIRMED', 'ARCHIVED')),
  constraint ck_eval_suite_pass_threshold check (pass_threshold >= 0 and pass_threshold <= 100),
  constraint fk_eval_suite_agent foreign key (agent_id) references agent_definition(id),
  constraint fk_eval_suite_workflow_version foreign key (workflow_version_id) references workflow_version(id)
);

create index idx_eval_suite_agent_workflow_node on eval_suite(agent_id, workflow_version_id, node_id);
create index idx_eval_suite_status on eval_suite(status);

create table eval_case (
  id bigint generated by default as identity primary key,
  suite_id bigint not null,
  case_no varchar(64) not null,
  title varchar(200) not null,
  input_json jsonb not null,
  reference_answer_json jsonb,
  assertions_json jsonb not null default '[]'::jsonb,
  score_rule_json jsonb not null default '{}'::jsonb,
  critical boolean not null default false,
  confirm_status varchar(30) not null,
  source_agent_run_id bigint,
  source_node_run_id bigint,
  source_workflow_version_id bigint,
  source_node_id varchar(128),
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_eval_case_case_no unique (suite_id, case_no),
  constraint ck_eval_case_confirm_status check (
    confirm_status in ('USER_CREATED', 'USER_CONFIRMED', 'AI_DRAFT_PENDING', 'ARCHIVED')
  ),
  constraint fk_eval_case_suite foreign key (suite_id) references eval_suite(id),
  constraint fk_eval_case_source_agent_run foreign key (source_agent_run_id) references agent_run(id),
  constraint fk_eval_case_source_node_run foreign key (source_node_run_id) references node_run(id),
  constraint fk_eval_case_source_workflow_version
    foreign key (source_workflow_version_id) references workflow_version(id)
);

create index idx_eval_case_suite_confirm_status on eval_case(suite_id, confirm_status);
create index idx_eval_case_suite_critical on eval_case(suite_id, critical);
create index idx_eval_case_source_node_run on eval_case(source_node_run_id);
create index idx_eval_case_source_workflow_node on eval_case(source_workflow_version_id, source_node_id);

create table eval_run (
  id bigint generated by default as identity primary key,
  run_no varchar(64) not null,
  suite_id bigint not null,
  agent_id bigint not null,
  workflow_version_id bigint not null,
  node_id varchar(128) not null,
  agent_run_id bigint,
  status varchar(20) not null,
  total_case_count integer not null default 0,
  passed_case_count integer not null default 0,
  failed_case_count integer not null default 0,
  pass_rate numeric(5,2) not null default 0,
  summary text not null default '',
  error_message text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint,
  constraint uq_eval_run_run_no unique (run_no),
  constraint ck_eval_run_status check (
    status in ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELED')
  ),
  constraint fk_eval_run_suite foreign key (suite_id) references eval_suite(id),
  constraint fk_eval_run_agent foreign key (agent_id) references agent_definition(id),
  constraint fk_eval_run_workflow_version foreign key (workflow_version_id) references workflow_version(id),
  constraint fk_eval_run_agent_run foreign key (agent_run_id) references agent_run(id)
);

create index idx_eval_run_suite_started_at_desc on eval_run(suite_id, started_at desc);
create index idx_eval_run_agent_status_started_at_desc on eval_run(agent_id, status, started_at desc);
create index idx_eval_run_workflow_node_started_at_desc
  on eval_run(workflow_version_id, node_id, started_at desc);

alter table trace_event
  add constraint fk_trace_event_eval_run foreign key (eval_run_id) references eval_run(id);

create table eval_case_result (
  id bigint generated by default as identity primary key,
  eval_run_id bigint not null,
  eval_case_id bigint not null,
  output_json jsonb,
  assertion_result_json jsonb not null default '{}'::jsonb,
  score_result_json jsonb not null default '{}'::jsonb,
  passed boolean not null default false,
  error_message text not null default '',
  duration_ms bigint,
  created_at timestamptz not null default now(),
  constraint uq_eval_case_result unique (eval_run_id, eval_case_id),
  constraint fk_eval_case_result_eval_run foreign key (eval_run_id) references eval_run(id),
  constraint fk_eval_case_result_eval_case foreign key (eval_case_id) references eval_case(id)
);

create index idx_eval_case_result_eval_run on eval_case_result(eval_run_id);
create index idx_eval_case_result_eval_case on eval_case_result(eval_case_id);
create index idx_eval_case_result_passed on eval_case_result(passed);
